### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by sean24YT** [kiwi201345/GTAV-1.64-Base#1]
dont stay open just flickers then wont open agen... platform epic and social

**Comment by kiwi201345** [comment]
The base requires some textures which is why you probably are having issues try looking for the drawsprite function and changing the texture ID's there

**Comment by sean24YT** [comment]
can you send me to the updated ones? why they broken if its updated?

**Comment by kiwi201345** [comment]
If you don't know how to change basic textures then that's down to you the code is functional. 

Textures are easily changed as mentioned just change the texture ID's and your all set
